# Generated by Django 4.2.4 on 2023-08-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='current_job_city',
            new_name='preferred_job_city',
        ),
    ]
